thinkful-ei-narwhal/penny-thoughts-server

- src/app.js
made unprotected route to check it works
> unProtected heloRoute

- package.json
- added "migrate:test:cesar": "set NODE_ENV=test&&npm run migrate" to package.json
> cesars test migrate

- example.env
fixed a name for people setting up the db's
> fixed example env

- src/users-endpoint/usersRouter.js
- src/users-endpoint/usersService.js
> debugged delete functionality on backend

- src/users-endpoint/usersService.js
-made error messages more concise for the user!
> registration fix

- src/messages-endpoint/messages-router.js
- src/users-endpoint/usersRouter.js
- src/users-endpoint/usersService.js
Finished CRUD ops for User Messages:
These are the only known issues/edge cases for this set of CRUD:
1. ID for individual messages is currently passed in the form of req.body.id - Some refactoring may be necessary if we can't/won't pass this from the front end but this way makes sense as we are not using req.match.params.id anywhere in our client. :)
2. TensorFlow MUST be hooked up to the PATCH endpoint in messages-router, as we can edit the message with toxic content and it will currently be patched in the database without any form of verification.
> User messages crud

- src/users-endpoint/usersService.js
I made the regex better I think
> fixed regex

- src/messages-endpoint/messages-service.js
added filter to oneRandomMessage
> added filter to random one

- src/messages-endpoint/messages-router.js
- src/messages-endpoint/messages-service.js
> Debugged PATCH for Users Messages in UserSettings

- src/messages-endpoint/messages-service.js
> fixed various things

- src/messages-endpoint/messages-router.js
- src/messages-endpoint/messages-service.js
> added a flagging service

- src/messages-endpoint/messages-router.js
Now passes in a new Date() for when modified.  Also cleaned up the service a little.
> added new date for edit post

- src/users-endpoint/usersRouter.js
- src/users-endpoint/usersService.js
finish patch with encryption for full_name and email
> User settings patch

- src/messages-endpoint/messages-service.js
- src/users-endpoint/usersRouter.js
- src/users-endpoint/usersService.js
plain and simple - removed console logs
> removed console.logs

- src/messages-endpoint/messages-router.js
push from yesterdays master working state
> pushing master from 7-9-2020

- src/auth/authRouter.js
- src/users-endpoint/usersRouter.js
I have stressed this OVER and OVER again.  Please use proper res codes because this is a silly mistake that causes other people problems.
> fixed res code that broke stuff

- migrations/001.do.create_users.sql
- migrations/002.do.create_messages.sql
- src/messages-endpoint/messages-service.js
- test/app.spec.js
- test/auth-endpoints.spec.js
- test/messages-endpoints.specs.js
- test/setup.js
- test/test-helpers.js
test helpers work
changed to make date modified null
serialized had to remove xss on date modified and date created
> Test helpers

- src/messages-endpoint/messages-router.js
- test/messages-endpoints.spec.js
bad tensorflow test errors work
> bad tensorflow test errors work

- src/messages-endpoint/messages-router.js
- test/messages-endpoints.spec.js
fixed missing key errors and 70 test work
> Missing key

- src/users-endpoint/usersRouter.js
removed a console log.  should be clean now
> removed unecc console logs

- README.md
> added link to client repo

- src/messages-endpoint/messages-router.js
- src/users-endpoint/usersRouter.js
there never needed to be authentication on Public route for reporting...otherwise they are always unauthorized.
> reporting no longer requires authenticaion

- test/protected-endpoints.spec.js
removed report from protected endpoints
> removed report from protected endpoints
